name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set timestamp variable
        run: echo "IMAGE_TAG=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Set up Maven Authentication for GitHub Packages
        run: |
          mkdir -p ~/.m2
          echo "<settings><servers><server><id>github</id><username>${{ github.actor }}</username><password>${{ secrets.SECRET_TOKEN }}</password></server></servers></settings>" > ~/.m2/settings.xml

      - name: Build Spring Boot JAR
        run: mvn clean package -DskipTests --settings ~/.m2/settings.xml

      - name: Verify JAR Exists
        run: ls -lah target/

      - name: Log in to GitHub Container Registry
        run: echo "${{ secrets.SECRET_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/serviceapp"
          docker build -t $IMAGE_NAME:${{ env.IMAGE_TAG }} .

      - name: Push Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/serviceapp"
          docker push $IMAGE_NAME:${{ env.IMAGE_TAG }}
